/// Flutter icons GuitarIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GuitarIcons
///      fonts:
///       - asset: fonts/GuitarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GuitarIcons {
  GuitarIcons._();

  static const _kFontFam = 'GuitarIcons';
  static const String? _kFontPkg = null;

  static const IconData two_music_notes = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_bars = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData generator = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
